[tool.poetry]
name = "portfolio-agent"
version = "0.1.0"
description = "..."
authors = ["You <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.14"
langgraph = "^0.6.6"
redis = ">=6.0.0,<7.0.0"
msgpack = "^1.0.5"

# Optional runtime dependencies — mark them optional here (no extras syntax in the names)
openai = { version = "^1.0.0", optional = true }
langchain = { version = "^0.3.0", optional = true }
pgvector = { version = "^0.4.0", optional = true }
psycopg = { version = "^3.1.0", extras = ["binary"], optional = true }  # if you need psycopg[binary]

[tool.poetry.extras]
# extras names must be plain identifiers and must reference the dependency *names* above
llm = ["openai", "langchain"]
vector = ["pgvector"]
postgres = ["psycopg"]
