"""
Persona Agent for portfolio-agent.

This module provides response generation with personality and context awareness.
"""

import logging
import re
from typing import Dict, Any, List, Optional
from dataclasses import dataclass
from enum import Enum

from ..text_matching import extract_terms, keyword_overlap, non_discriminative_terms

logger = logging.getLogger(__name__)

class PersonaType(Enum):
    """Available persona types."""
    PROFESSIONAL = "professional"
    FRIENDLY = "friendly"
    TECHNICAL = "technical"
    CASUAL = "casual"
    ENTHUSIASTIC = "enthusiastic"

@dataclass
class PersonaRequest:
    """Request for persona response generation."""
    query: str
    documents: List[Dict[str, Any]]
    persona_type: PersonaType = PersonaType.PROFESSIONAL
    max_response_length: int = 500
    include_sources: bool = True
    context: Optional[Dict[str, Any]] = None

@dataclass
class PersonaResponse:
    """Response generated by persona agent."""
    response: str
    sources: List[Dict[str, Any]]
    persona_used: PersonaType
    response_time: float
    metadata: Dict[str, Any]

class PersonaAgent:
    """Persona agent for generating contextual responses with personality."""
    
    def __init__(
        self,
        default_persona: PersonaType = PersonaType.PROFESSIONAL,
        max_response_time: float = 10.0
    ):
        """Initialize persona agent."""
        self.default_persona = default_persona
        self.max_response_time = max_response_time
        
        # Define persona templates
        self.persona_templates = {
            PersonaType.PROFESSIONAL: {
                "greeting": "Hello! I'd be happy to help you with that.",
                "transition": "Based on my experience and background,",
                "conclusion": "I hope this information is helpful. Feel free to ask if you need more details.",
                "tone": "professional, informative, concise"
            },
            PersonaType.FRIENDLY: {
                "greeting": "Hi there! Great question!",
                "transition": "From what I know,",
                "conclusion": "Hope that helps! Let me know if you want to know more about anything.",
                "tone": "warm, approachable, conversational"
            },
            PersonaType.TECHNICAL: {
                "greeting": "Let me break that down for you technically.",
                "transition": "From a technical perspective,",
                "conclusion": "That's the technical overview. Happy to dive deeper into any specific aspect.",
                "tone": "precise, detailed, technical"
            }
        }
        
        logger.info("Persona agent initialized")
    
    def generate_response(
        self,
        request: PersonaRequest,
        context: Optional[Dict[str, Any]] = None
    ) -> PersonaResponse:
        """Generate a response with the specified persona."""
        import time
        start_time = time.time()
        
        logger.info(f"Generating response with {request.persona_type.value} persona")
        
        try:
            # Get persona template
            persona_template = self.persona_templates.get(
                request.persona_type, 
                self.persona_templates[self.default_persona]
            )
            
            # Extract query-aligned evidence from documents.
            evidence_items = self._extract_evidence(request.documents, request.query)
            evidence_strength = self._assess_evidence_strength(evidence_items)
            
            # Generate response based on persona
            response = self._generate_persona_response(
                query=request.query,
                evidence_items=evidence_items,
                evidence_strength=evidence_strength,
                include_sources=request.include_sources,
                persona_template=persona_template,
                max_length=request.max_response_length
            )
            
            # Prepare sources from the evidence we actually used when possible.
            sources = []
            if request.include_sources:
                evidence_ids = {item["id"] for item in evidence_items}
                source_documents = [
                    document for document in request.documents
                    if not evidence_ids or document.get("id", "") in evidence_ids
                ]
                sources = self._prepare_sources(source_documents)
            
            response_time = time.time() - start_time
            
            # Create response
            result = PersonaResponse(
                response=response,
                sources=sources,
                persona_used=request.persona_type,
                response_time=response_time,
                metadata={
                    "documents_used": len(request.documents),
                    "evidence_used": len(evidence_items),
                    "evidence_source_ids": [item["id"] for item in evidence_items],
                    "evidence_sources": [item["source"] for item in evidence_items],
                    "evidence_strength": evidence_strength,
                    "max_length": request.max_response_length,
                    "include_sources": request.include_sources,
                    "context_provided": context is not None
                }
            )
            
            logger.info(f"Generated response in {response_time:.3f}s")
            return result
            
        except Exception as e:
            logger.error(f"Error during response generation: {e}")
            # Return fallback response
            return PersonaResponse(
                response="I apologize, but I'm having trouble generating a response right now. Please try again.",
                sources=[],
                persona_used=request.persona_type,
                response_time=time.time() - start_time,
                metadata={"error": str(e)}
            )
    
    def _extract_evidence(
        self,
        documents: List[Dict[str, Any]],
        query: str
    ) -> List[Dict[str, Any]]:
        """Extract source-backed evidence snippets from retrieved documents."""
        if not documents:
            return []

        ignored_terms = non_discriminative_terms(query, [doc.get("content", "") for doc in documents[:5]])
        query_terms = self._query_terms(query, ignored_terms=ignored_terms)
        evidence_items: List[Dict[str, Any]] = []

        for doc in documents[:5]:
            content = doc.get("content", "")
            if not content:
                continue

            snippet, overlap = self._best_snippet(content, query_terms)
            if not snippet:
                continue

            metadata = doc.get("metadata", {})
            evidence_items.append(
                {
                    "id": doc.get("id", ""),
                    "source": metadata.get("source") or doc.get("id", ""),
                    "score": float(doc.get("score", 0.0)),
                    "overlap": overlap,
                    "snippet": snippet,
                }
            )

        evidence_items.sort(key=lambda item: (item["overlap"], item["score"]), reverse=True)
        return evidence_items[:3]

    def _assess_evidence_strength(self, evidence_items: List[Dict[str, Any]]) -> str:
        """Classify how strong the currently available evidence is."""
        if not evidence_items:
            return "none"

        top_item = evidence_items[0]
        if top_item["overlap"] >= 2 or top_item["score"] >= 0.8:
            return "strong"
        if top_item["overlap"] >= 1 or top_item["score"] >= 0.6:
            return "moderate"
        return "weak"
    
    def _generate_persona_response(
        self,
        query: str,
        evidence_items: List[Dict[str, Any]],
        evidence_strength: str,
        include_sources: bool,
        persona_template: Dict[str, str],
        max_length: int
    ) -> str:
        """Generate response using persona template."""
        response_parts = [persona_template["greeting"]]
        response_parts.append(persona_template["transition"])

        if evidence_items and evidence_strength != "weak":
            evidence_text = " ".join(
                self._format_evidence_item(item, include_sources=include_sources)
                for item in evidence_items
            )
            response_parts.append(f"the indexed sources support the following: {evidence_text}")
        elif evidence_items:
            tentative = self._format_evidence_item(evidence_items[0], include_sources=include_sources)
            response_parts.append(
                "I found only limited support in the indexed sources, so this may be incomplete. "
                f"The strongest matching evidence is: {tentative}"
            )
        else:
            response_parts.append(
                "I don't have enough source-backed information in the indexed documents to answer that confidently."
            )

        response_parts.append(persona_template["conclusion"])
        full_response = " ".join(response_parts)
        
        if len(full_response) > max_length:
            full_response = self._truncate_response(full_response, max_length)
        
        return full_response

    def _format_evidence_item(self, item: Dict[str, Any], *, include_sources: bool) -> str:
        snippet = item["snippet"]
        if include_sources:
            return f"(source: {item['source']}) {snippet}"
        return snippet

    def _query_terms(self, query: str, *, ignored_terms=None) -> List[str]:
        return extract_terms(query, ignored_terms=ignored_terms)

    def _best_snippet(self, content: str, query_terms: List[str]) -> tuple[str, int]:
        segments = [segment.strip() for segment in re.split(r"(?<=[.!?])\s+|\n+", content) if segment.strip()]
        if not segments:
            return "", 0

        if not query_terms:
            best = segments[0]
            return self._truncate(best), 0

        best_segment = ""
        best_overlap = -1
        for segment in segments:
            overlap = keyword_overlap(" ".join(query_terms), segment)
            if overlap > best_overlap:
                best_segment = segment
                best_overlap = overlap

        if best_overlap <= 0:
            return "", 0

        return self._truncate(best_segment), best_overlap

    def _truncate(self, text: str, max_chars: int = 220) -> str:
        if len(text) <= max_chars:
            return text
        return text[:max_chars].rstrip() + "..."

    def _truncate_response(self, text: str, max_chars: int) -> str:
        if len(text) <= max_chars:
            return text

        truncated = text[: max_chars - 3].rstrip()
        last_space = truncated.rfind(" ")
        if last_space > max_chars * 0.6:
            truncated = truncated[:last_space]
        return truncated + "..."
    
    def _prepare_sources(self, documents: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Prepare source information from documents."""
        sources = []
        for doc in documents:
            source_info = {
                "id": doc.get("id", ""),
                "score": doc.get("score", 0),
                "rank": doc.get("rank", 0)
            }
            
            # Add metadata if available
            metadata = doc.get("metadata", {})
            if metadata:
                source_info.update({
                    "source": metadata.get("source", ""),
                    "title": metadata.get("title", ""),
                    "content_type": metadata.get("content_type", "")
                })
            
            sources.append(source_info)
        
        return sources
    
    def get_persona_stats(self) -> Dict[str, Any]:
        """Get persona agent statistics."""
        return {
            "default_persona": self.default_persona.value,
            "available_personas": [persona.value for persona in self.persona_templates.keys()],
            "max_response_time": self.max_response_time,
            "total_templates": len(self.persona_templates)
        }

# Convenience function for easy access
def create_persona_agent(**kwargs) -> PersonaAgent:
    """Create a persona agent with default settings."""
    return PersonaAgent(**kwargs)
