"""
Persona Agent for portfolio-agent.

This module provides response generation with personality and context awareness.
"""

import logging
from typing import Dict, Any, List, Optional
from dataclasses import dataclass
from enum import Enum

logger = logging.getLogger(__name__)

class PersonaType(Enum):
    """Available persona types."""
    PROFESSIONAL = "professional"
    FRIENDLY = "friendly"
    TECHNICAL = "technical"
    CASUAL = "casual"
    ENTHUSIASTIC = "enthusiastic"

@dataclass
class PersonaRequest:
    """Request for persona response generation."""
    query: str
    documents: List[Dict[str, Any]]
    persona_type: PersonaType = PersonaType.PROFESSIONAL
    max_response_length: int = 500
    include_sources: bool = True
    context: Optional[Dict[str, Any]] = None

@dataclass
class PersonaResponse:
    """Response generated by persona agent."""
    response: str
    sources: List[Dict[str, Any]]
    persona_used: PersonaType
    response_time: float
    metadata: Dict[str, Any]

class PersonaAgent:
    """Persona agent for generating contextual responses with personality."""
    
    def __init__(
        self,
        default_persona: PersonaType = PersonaType.PROFESSIONAL,
        max_response_time: float = 10.0
    ):
        """Initialize persona agent."""
        self.default_persona = default_persona
        self.max_response_time = max_response_time
        
        # Define persona templates
        self.persona_templates = {
            PersonaType.PROFESSIONAL: {
                "greeting": "Hello! I'd be happy to help you with that.",
                "transition": "Based on my experience and background,",
                "conclusion": "I hope this information is helpful. Feel free to ask if you need more details.",
                "tone": "professional, informative, concise"
            },
            PersonaType.FRIENDLY: {
                "greeting": "Hi there! Great question!",
                "transition": "From what I know,",
                "conclusion": "Hope that helps! Let me know if you want to know more about anything.",
                "tone": "warm, approachable, conversational"
            },
            PersonaType.TECHNICAL: {
                "greeting": "Let me break that down for you technically.",
                "transition": "From a technical perspective,",
                "conclusion": "That's the technical overview. Happy to dive deeper into any specific aspect.",
                "tone": "precise, detailed, technical"
            }
        }
        
        logger.info("Persona agent initialized")
    
    def generate_response(
        self,
        request: PersonaRequest,
        context: Optional[Dict[str, Any]] = None
    ) -> PersonaResponse:
        """Generate a response with the specified persona."""
        import time
        start_time = time.time()
        
        logger.info(f"Generating response with {request.persona_type.value} persona")
        
        try:
            # Get persona template
            persona_template = self.persona_templates.get(
                request.persona_type, 
                self.persona_templates[self.default_persona]
            )
            
            # Extract relevant information from documents
            relevant_info = self._extract_relevant_info(request.documents, request.query)
            
            # Generate response based on persona
            response = self._generate_persona_response(
                query=request.query,
                relevant_info=relevant_info,
                persona_template=persona_template,
                max_length=request.max_response_length
            )
            
            # Prepare sources
            sources = []
            if request.include_sources:
                sources = self._prepare_sources(request.documents)
            
            response_time = time.time() - start_time
            
            # Create response
            result = PersonaResponse(
                response=response,
                sources=sources,
                persona_used=request.persona_type,
                response_time=response_time,
                metadata={
                    "documents_used": len(request.documents),
                    "max_length": request.max_response_length,
                    "include_sources": request.include_sources,
                    "context_provided": context is not None
                }
            )
            
            logger.info(f"Generated response in {response_time:.3f}s")
            return result
            
        except Exception as e:
            logger.error(f"Error during response generation: {e}")
            # Return fallback response
            return PersonaResponse(
                response="I apologize, but I'm having trouble generating a response right now. Please try again.",
                sources=[],
                persona_used=request.persona_type,
                response_time=time.time() - start_time,
                metadata={"error": str(e)}
            )
    
    def _extract_relevant_info(
        self,
        documents: List[Dict[str, Any]],
        query: str
    ) -> str:
        """Extract relevant information from documents."""
        if not documents:
            return "I don't have specific information about that topic."
        
        # Combine content from top documents
        relevant_content = []
        for doc in documents[:3]:  # Use top 3 documents
            content = doc.get("content", "")
            if content:
                # Truncate long content
                if len(content) > 200:
                    content = content[:200] + "..."
                relevant_content.append(content)
        
        return " ".join(relevant_content)
    
    def _generate_persona_response(
        self,
        query: str,
        relevant_info: str,
        persona_template: Dict[str, str],
        max_length: int
    ) -> str:
        """Generate response using persona template."""
        # Start with greeting
        response_parts = [persona_template["greeting"]]
        
        # Add transition
        response_parts.append(persona_template["transition"])
        
        # Add relevant information
        if relevant_info and relevant_info != "I don't have specific information about that topic.":
            response_parts.append(relevant_info)
        else:
            response_parts.append("I don't have specific information about that topic in my knowledge base.")
        
        # Add conclusion
        response_parts.append(persona_template["conclusion"])
        
        # Combine and truncate if necessary
        full_response = " ".join(response_parts)
        
        if len(full_response) > max_length:
            # Truncate at sentence boundary
            sentences = full_response.split('. ')
            truncated = []
            current_length = 0
            
            for sentence in sentences:
                if current_length + len(sentence) + 2 <= max_length:  # +2 for '. '
                    truncated.append(sentence)
                    current_length += len(sentence) + 2
                else:
                    break
            
            full_response = '. '.join(truncated)
            if not full_response.endswith('.'):
                full_response += '.'
        
        return full_response
    
    def _prepare_sources(self, documents: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Prepare source information from documents."""
        sources = []
        for doc in documents:
            source_info = {
                "id": doc.get("id", ""),
                "score": doc.get("score", 0),
                "rank": doc.get("rank", 0)
            }
            
            # Add metadata if available
            metadata = doc.get("metadata", {})
            if metadata:
                source_info.update({
                    "source": metadata.get("source", ""),
                    "title": metadata.get("title", ""),
                    "content_type": metadata.get("content_type", "")
                })
            
            sources.append(source_info)
        
        return sources
    
    def get_persona_stats(self) -> Dict[str, Any]:
        """Get persona agent statistics."""
        return {
            "default_persona": self.default_persona.value,
            "available_personas": [persona.value for persona in self.persona_templates.keys()],
            "max_response_time": self.max_response_time,
            "total_templates": len(self.persona_templates)
        }

# Convenience function for easy access
def create_persona_agent(**kwargs) -> PersonaAgent:
    """Create a persona agent with default settings."""
    return PersonaAgent(**kwargs)