name: Publish to PyPI

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: "2.1.4"
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Validate Poetry files
        run: poetry check --lock

      - name: Build package
        run: poetry build

      - name: Publish with Poetry
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN }}
        run: poetry publish
