name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish with Poetry
        uses: JRubics/poetry-publish@v2.1
        with:
          pypi_token: ${{ secrets.POETRY_PYPI_TOKEN }}
